# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:todos
    url: jdbc:h2:file:E:\Projects\DB\todos\todos.db;MV_STORE=false
    platform: h2
    username: root
    password: toor
  devtools:
    restart:
      enabled: true

server:
  port: 8000